# Generated by Django 6.0.4 on 2026-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
