# Generated by Django 6.0.4 on 2026-05-02 13:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dashboard_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=10)),
                ('output', models.TextField(blank=True, null=True)),
                ('error_output', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('stdin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_answer', models.TextField()),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='general', max_length=50)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('topic', 'id')},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('track', 'order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='usertopicprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='core.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topics',
            field=models.ManyToManyField(related_name='tests', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertopicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.topic'),
        ),
        migrations.AlterField(
            model_name='usertopicprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', '-occurred_at'], name='idx_user_activity'),
        ),
        migrations.AddIndex(
            model_name='companytarget',
            index=models.Index(fields=['user', 'is_active'], name='idx_user_active_company'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'completed_at'], name='idx_user_completed_attempts'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='idx_user_test'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='idx_user_correct'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'question'], name='idx_user_question'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
        migrations.AddIndex(
            model_name='usertopicprogress',
            index=models.Index(fields=['user', 'is_completed'], name='idx_user_completed'),
        ),
        migrations.AddConstraint(
            model_name='usertopicprogress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic_progress'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewqa',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='core.interviewsession'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_code_subs'),
        ),
    ]
