# Generated by Django 6.0.4 on 2026-05-28 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_codesubmission_interviewqa_interviewsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='my_resume.pdf', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.IntegerField(default=68)),
                ('ats_score', models.IntegerField(default=65)),
                ('recruiter_score', models.IntegerField(default=62)),
                ('analysis_data', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
