# Generated by Django 6.0.4 on 2026-05-28 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employability_score', models.IntegerField(default=74)),
                ('competency_score', models.IntegerField(default=78)),
                ('recruiter_trust_score', models.CharField(default='High', max_length=20)),
                ('readiness_tier', models.CharField(default='Product Company Ready', max_length=50)),
                ('passport_data', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('public_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
