# Generated by Django 6.0.4 on 2026-05-28 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userpassport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_score', models.IntegerField(default=75)),
                ('trust_score', models.IntegerField(default=80)),
                ('readiness_level', models.CharField(default='High Confidence', max_length=50)),
                ('verification_date', models.DateField(auto_now_add=True)),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('cryptographic_hash', models.CharField(max_length=100, unique=True)),
                ('evidence_data', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('sharing_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
