# Generated by Django 6.0.4 on 2026-05-29 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usercertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_strength', models.IntegerField(default=75)),
                ('recruiter_attractiveness', models.IntegerField(default=70)),
                ('competitiveness_score', models.IntegerField(default=68)),
                ('selected_template', models.CharField(default='SDE Portfolio', max_length=100)),
                ('public_url_slug', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('analytics', models.JSONField(default=dict)),
                ('copilot_advice', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('tech_stack', models.JSONField(default=list)),
                ('difficulty', models.CharField(default='Medium', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('milestones', models.JSONField(default=list)),
                ('kanban_board', models.JSONField(default=dict)),
                ('impact_scores', models.JSONField(default=dict)),
                ('evaluation_report', models.JSONField(default=dict)),
                ('deployment_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('architecture_diagram', models.TextField(blank=True, null=True)),
                ('resume_sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
