# Generated by Django 6.0.4 on 2026-05-29 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userportfolio_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('topics', models.JSONField(default=list)),
                ('companies', models.JSONField(default=list)),
                ('relevance_score', models.IntegerField(default=90)),
                ('readiness_impact', models.IntegerField(default=3)),
                ('description', models.TextField()),
                ('constraints', models.JSONField(default=list)),
                ('examples', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('starter_code', models.JSONField(default=dict)),
                ('testcases', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(default='Accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('sql', 'SQL')], default='python', max_length=15),
        ),
        migrations.CreateModel(
            name='CodingContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('problems', models.ManyToManyField(related_name='contests', to='core.codingproblem')),
            ],
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.codingproblem'),
        ),
    ]
