# Generated by Django 6.0.4 on 2026-05-29 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_codingproblem_codesubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='testcases',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='function_signature',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.codingproblem')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
