# Generated by Django 6.0.4 on 2026-05-30 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='interview_frequency',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='target_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TopicRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('cheat_sheet_markdown', models.TextField(blank=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content_markdown', models.TextField()),
                ('section_type', models.CharField(choices=[('overview', 'Overview'), ('learn', 'Learn'), ('guided', 'Guided Examples')], default='overview', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.topic')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TopicVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Interactive Visualization', max_length=180)),
                ('visualization_type', models.CharField(choices=[('sliding-window', 'Sliding Window'), ('graph-dfs', 'Graph DFS/BFS'), ('linked-list-cycle', 'Linked List Cycle'), ('aptitude-profit', 'Aptitude Profit/Loss'), ('generic', 'Generic')], default='generic', max_length=30)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visualization', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_for', to='core.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.topic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('topic', 'prerequisite'), name='unique_topic_prerequisite')],
            },
        ),
    ]
