# Generated by Django 6.0.4 on 2026-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='domain',
            field=models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('aptitude', 'Aptitude & Logical'), ('core_cs', 'Core Computer Science'), ('career', 'Career & Behavioral')], default='dsa', max_length=20),
        ),
    ]
