# Generated by Django 6.0.4 on 2026-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='acceptance_rate',
            field=models.FloatField(default=50.0),
        ),
    ]
