# Generated by Django 6.0.4 on 2026-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_codingproblem_acceptance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='function_name',
            field=models.CharField(default='solve', help_text='Name of the function to call in the runner', max_length=100),
        ),
    ]
