# Generated by Django 6.0.4 on 2026-05-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_codingproblem_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingcontest',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingcontest',
            name='platform',
            field=models.CharField(default='PrepSmart', max_length=100),
        ),
        migrations.AlterField(
            model_name='codingcontest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='contests', to='core.codingproblem'),
        ),
    ]
