# Generated by Django 6.0.4 on 2026-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
