from django.urls import path
from .views import (
    TrackListView,
    TopicByTrackView,
    CompleteTopicView,
    TrackProgressView,
    QuestionByTopicView,
    SubmitAnswerView,
    WeakTopicView,
    TestDetailView,
    TestListView,
    StartTestView,
    SubmitTestView,
    TopicAccuracyView,
    OverallPerformanceView,
    AnalyticsDashboardView,
    AIExplanationView,
    CompaniesView,
    CompanyTargetUpdateView,
    CompanyDetailAPIView,
    FullAnalyticsView,
    LearningPathView,
    PracticeDashboardView,
    TopicProgressUpdateView,
    AdminOverviewView,
    AdminUserUpdateView,
    AdminContentView,
    AdminTrackDetailView,
    AdminTopicDetailView,
    AdminQuestionDetailView,
    AdminTestDetailView,
    AdminCompanyTargetView,
    AdminCompanyTargetDetailView,
    CodeExecuteView,
    CodeSubmissionListView,
    InterviewStartView,
    InterviewNextQuestionView,
    InterviewSubmitAnswerView,
    InterviewEndView,
    InterviewHistoryView,
    InterviewConfigView,
    HealthView,
    LandingView,
    CodeWorkspaceView,
    ResumeOverviewView,
    PassportOverviewView,
    PublicPassportView,
    VerificationDashboardView,
    PublicCertificateView,
    PortfolioDashboardView,
    PublicPortfolioView,
    CodeLabDashboardView,
    ProblemListView,
    ProblemDetailView,
    CodeRunView,
    CodeSubmitView,
    ProblemSubmitView,
    AIMentorView,
    ProblemBookmarkToggleView,
    ProblemSubmissionListView,
    ProblemEditorialView,
    ContestListView,
    ContestLeaderboardView,
    SnippetListView,
    SnippetDetailView,
    PrepCurrentTopicView,
    PrepTopicJourneyView,
    PrepRoadmapsView,
    PrepMilestonesView,
    PrepCompleteTopicView,
    PrepTopicDetailView,
    PrepTopicCompleteView,
    PrepTopicQuizSubmitView,
    PrepTopicDraftView,
    PrepTopicAIContextView,
    PrepTopicAIChatView,
    ProblemsByTopicView,
    UserProgressView,
)

urlpatterns = [
    path('prep/current-topic/', PrepCurrentTopicView.as_view()),
    path('prep/topic-journey/', PrepTopicJourneyView.as_view()),
    path('prep/roadmaps/', PrepRoadmapsView.as_view()),
    path('prep/milestones/', PrepMilestonesView.as_view()),
    path('prep/complete-topic/', PrepCompleteTopicView.as_view()),
    path('prep/topic/<slug:slug>/', PrepTopicDetailView.as_view()),
    path('prep/topic/<slug:slug>/complete/', PrepTopicCompleteView.as_view()),
    path('prep/topic/<slug:slug>/drafts/', PrepTopicDraftView.as_view()),
    path('prep/topic/<slug:slug>/quiz/submit/', PrepTopicQuizSubmitView.as_view()),
    path('prep/topic/<slug:slug>/ai-context/', PrepTopicAIContextView.as_view()),
    path('prep/topic/<slug:slug>/ai-chat/', PrepTopicAIChatView.as_view()),
    path('problems/by-topic/<int:topic_id>/', ProblemsByTopicView.as_view()),
    path('user/progress/', UserProgressView.as_view()),
    path('health/', HealthView.as_view()),
    path('landing/', LandingView.as_view()),
    path('learning-path/', LearningPathView.as_view()),
    path('practice/', PracticeDashboardView.as_view()),
    path('analytics/full/', FullAnalyticsView.as_view()),
    path('companies/', CompaniesView.as_view()),
    path('companies/<str:company_name>/', CompanyTargetUpdateView.as_view()),
    path('companies/<str:company_name>/details/', CompanyDetailAPIView.as_view()),
    path('admin/overview/', AdminOverviewView.as_view()),
    path('admin/users/<int:user_id>/', AdminUserUpdateView.as_view()),
    path('admin/content/', AdminContentView.as_view()),
    path('admin/tracks/<int:track_id>/', AdminTrackDetailView.as_view()),
    path('admin/topics/<int:topic_id>/', AdminTopicDetailView.as_view()),
    path('admin/questions/<int:question_id>/', AdminQuestionDetailView.as_view()),
    path('admin/tests/<int:test_id>/', AdminTestDetailView.as_view()),
    path('admin/company-targets/', AdminCompanyTargetView.as_view()),
    path('admin/company-targets/<int:target_id>/', AdminCompanyTargetDetailView.as_view()),
    path('tracks/', TrackListView.as_view()),
    path('tracks/<int:track_id>/topics/', TopicByTrackView.as_view()),
    path('topics/<int:topic_id>/complete/', CompleteTopicView.as_view()),
    path('topics/<int:topic_id>/progress/', TopicProgressUpdateView.as_view()),
    path('tracks/<int:track_id>/progress/', TrackProgressView.as_view()),
    path('topics/<int:topic_id>/questions/', QuestionByTopicView.as_view()),
    path('questions/<int:question_id>/submit/', SubmitAnswerView.as_view()),
    path('weak-topics/', WeakTopicView.as_view()),
    path('tests/', TestListView.as_view()),
    path('tests/<int:test_id>/', TestDetailView.as_view()),
    path('tests/<int:test_id>/start/', StartTestView.as_view()),
    path('tests/submit/', SubmitTestView.as_view()),
    path('analytics/topic-accuracy/', TopicAccuracyView.as_view()),
    path('analytics/overall-performance/', OverallPerformanceView.as_view()),
    path('analytics/dashboard/', AnalyticsDashboardView.as_view()),
    path('ai/explain/', AIExplanationView.as_view()),
    path('code/execute/', CodeExecuteView.as_view()),
    path('code/workspace/', CodeWorkspaceView.as_view()),
    path('code/submissions/', CodeSubmissionListView.as_view()),
    path('interview/start/', InterviewStartView.as_view()),
    path('interview/config/', InterviewConfigView.as_view()),
    path('interview/question/', InterviewNextQuestionView.as_view()),
    path('interview/submit/', InterviewSubmitAnswerView.as_view()),
    path('interview/end/', InterviewEndView.as_view()),
    path('interview/history/', InterviewHistoryView.as_view()),
    path('resume/', ResumeOverviewView.as_view()),
    path('passport/', PassportOverviewView.as_view()),
    path('passport/shared/<str:token>/', PublicPassportView.as_view()),
    path('verification/', VerificationDashboardView.as_view()),
    path('verification/shared/<str:token>/', PublicCertificateView.as_view()),
    path('portfolio/', PortfolioDashboardView.as_view()),
    path('portfolio/shared/<str:slug>/', PublicPortfolioView.as_view()),
    path('code/dashboard/', CodeLabDashboardView.as_view()),
    path('code/problems/', ProblemListView.as_view()),
    path('code/problems/<slug:slug>/', ProblemDetailView.as_view()),
    path('code/problems/<slug:slug>/submit/', CodeSubmitView.as_view()),
    path('code/problems/<slug:slug>/run/', CodeRunView.as_view()),
    path('code/problems/<slug:slug>/submissions/', ProblemSubmissionListView.as_view()),
    path('code/problems/<slug:slug>/editorial/', ProblemEditorialView.as_view()),
    path('code/problems/<slug:slug>/bookmark/', ProblemBookmarkToggleView.as_view()),
    path('code/problems/<slug:slug>/ai-mentor/', AIMentorView.as_view()),
    path('code/contests/', ContestListView.as_view()),
    path('code/contests/<int:contest_id>/leaderboard/', ContestLeaderboardView.as_view()),
    path('code/snippets/', SnippetListView.as_view()),
    path('code/snippets/<int:pk>/', SnippetDetailView.as_view()),
    path('interview/end/', InterviewEndView.as_view()),
    path('interview/history/', InterviewHistoryView.as_view()),
]
